// import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header.js";
import Cover from "./components/cover.js";
import Services from "./components/services.js";
import Footer from "./components/footer.js";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-b from-skyBlue to-navyBlue ">
        <Header/>
        <Cover/>
        <Services/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
